# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('HTModel_rcpp_hello_world', PACKAGE = 'HTModel')
}

obj_cpp <- function(para, yi, yj) {
    .Call('HTModel_obj_cpp', PACKAGE = 'HTModel', para, yi, yj)
}

